### ISSUE TITLE
Issue in an Add the dependency to gradle file:

### ISSUE THREAD

**Issue by ibadurrahmantalha** [lapism/search#404]
i try below but not any of them is working:
implementation 'com.lapism.search:search: ASAP'
implementation 'com.lapism.search:search:1.0.0-alpha05'
implementation 'com.lapism.search:search:5.0.0-alpha05'

and many other but it not working. Please help

**Comment by lapism** [comment]
Yes, because I had to you close the old repository. But new dependency will be out asap. In the meantime you have to fork this repository.
