### ISSUE TITLE
The searchview is always focused on some devices

### ISSUE THREAD

**Issue by ydhnwb** [lapism/search#406]
I'm using the 1.0.0 version, all running well but on not on some device (ex: Asus Zenfone 3 with Android O).

In Zenfone 3, the searchview always focused even i called clearfocus. Here are the code

![gambar](https://user-images.githubusercontent.com/26734262/74565774-94ecd000-4fa4-11ea-8687-2d47f4e207b2.png)

and here is the bug on zenfone 3

![WhatsApp-Video-2020-02-15-at-329](https://user-images.githubusercontent.com/26734262/74566041-29efc900-4fa5-11ea-88e5-08299a770624.gif)

should look like this
![gambar](https://user-images.githubusercontent.com/26734262/74566458-142ed380-4fa6-11ea-8bb0-2614ec69b179.png)

**Comment by lapism** [comment]
Have you found anything ? Because I do not have these devices.

**Comment by ydhnwb** [comment]
I just realized that this problem is exists when the phone os is below Nougat (Android 7.0). I didnt find a way to fix it

**Comment by gzodx** [comment]
i use andrioid 8.0 and this still happends it always on focus

**Comment by lapism** [comment]
Ok. I will try it ASAP.

**Comment by lapism** [comment]
Try add this to your activity declaration in Manifest             android:windowSoftInputMode="adjustPan|adjustNothing" . Because I tried it in my app and it works on Oreo correctly.

**Comment by ydhnwb** [comment]
Will try it and let you know once i get home

**Comment by ydhnwb** [comment]
![Screenshot from 2020-03-02 17-09-51](https://user-images.githubusercontent.com/26734262/75666813-146ae680-5ca9-11ea-8936-6e0f759667cb.png)


The problem still exists event i added  android:windowSoftInputMode="adjustPan|adjustNothing" on Manifests (tested on Android 7 Emulator)
