### ISSUE TITLE
bintray version 2.0

### ISSUE THREAD

**Issue by lapism** [lapism/search#408]
Plugin bug probably

**Comment by Faltenreich** [comment]
Did you get in contact with the Bintray support? They are very helpful and respond relatively quick.

**Comment by Abdulrahman-N** [comment]
Any updates? I'm getting an error when trying to add the dependancy.

**Comment by lapism** [comment]
It should work now...

**Comment by lapism** [comment]
implementation 'com.lapism:search:2.0.0@aar'
