### ISSUE TITLE
Pressing back on the phone closes app

### ISSUE THREAD

**Issue by codejunk1e** [lapism/search#415]
When the search Widget is selected and active, pressing back doesn't make the widget close and lose focus, instead it closes the app. Tried adding this but it doesn't seem to work.
```
 @Override
    public void onBackPressed() {

        if (materialSearchView != null && materialSearchView.isFocused()){
            materialSearchView.clearFocus();
        }
        else {
            super.onBackPressed();
        }

    }
```

**Comment by lapism** [comment]
Add setClearOnBackPressed with true value

**Comment by codejunk1e** [comment]
setClearFocusOnBackPressed(true) worked. Was about to ask if there was a way to add a progress bar but I cannot see it in the search_view.xml. Thanks for the great library!

**Comment by lapism** [comment]
I am not planning to add a progressbar in near future , sorry :-). And you are welcome.
