### ISSUE TITLE
when clone library and load it, android studio give error

### ISSUE THREAD

**Issue by mousavi007** [lapism/search#416]
when clone repository my android studio give following error:

Plugin [id: 'com.android.library'] was not found in any of the following sources:

- Gradle Core Plugins (plugin is not in 'org.gradle' namespace)
- Plugin Repositories (plugin dependency must include a version number for this source)

**Comment by lapism** [comment]
That is because I have been using Android Studio 4.1. You have to change build.gradle for Android Studio 4.0.
