### ISSUE TITLE
Transparent Background

### ISSUE THREAD

**Issue by tamuseanmiller** [lapism/search#421]
I'm struggling to get the search bar by itself without any background. Is there any way to get the SearchView with an App Bar with a transparent background?
I've attached below what I was able to get to work.
![Screenshot_20210922-165344](https://user-images.githubusercontent.com/42820988/134427231-c5323598-d42c-4472-9279-822045bb30ae.png)

**Comment by lapism** [comment]
Hi,  

there is very a simple solution, do not use app:behavior and use transparent background for your appbar class.

**Comment by lapism** [comment]
Or...write and extend your own CoordinatorLayot.Behavior class or AppBar.Behavior class.

**Comment by tamuseanmiller** [comment]
Was able to get it to work, thanks!
