### ISSUE TITLE
How to make search bar rounded

### ISSUE THREAD

**Issue by doteq** [lapism/search#427]
In version 1.2.0 search bar is slightly rounded and there is new property to customize it. However, when i tried to set `search_radius` to a different value, for example 1dp, app is crashing and I'm getting an error inflating class caused by: `java.lang.NumberFormatException: For input string: "1.0dip"`. How to set full bar radius, like in previous versions?

**Comment by lapism** [comment]
Hi, sorry for that. It is a bug. I am going to release fixed version 1.2.1 in next hour.
